baseURL = "https://www.fitrianingrum.me/"
languageCode = "en-US"
title = "Blog and personal website of Fitrianingrum"
disqusShortname = ""
enableEmoji = true
enableGitInfo = true
pygmentsCodeFences = true
pygmentsStyle = "friendly"
summaryLength = 30 
googleAnalytics = "UA-163096145-1"
enableRobotsTXT = true
canonifyURLs = true

[related]
  threshold = 75
  includeNewer = true
  toLower = false
  indices = [
	{ name = "tags", weight = 100 },
	{ name = "date", weight = 10  }
  ]

[params]
    Author = "Fitrianingrum"
	Description = "blog and personal website"
    SiteTagline = "Coding, blogging"
    NavLinks = [
		{ url = "/post", title = "Blogs" },
        { url = "/contact", title = "Contact" }
    ]
    
[taxonomies]
    category = "categories"
    tag = "tags"

[permalinks]
	post = "post/:filename/"